### ISSUE TITLE
Chrome version error while running in Travis-CI

### ISSUE THREAD

**Issue by shlomiLan** [mherrmann/selenium-python-helium#24]
First of all, thanks for this great package, tried `selenium` in the past and found it too complex.

I managed to use this package locally, but when trying to run in. `Travis-CI`, I'm getting the following error:
```bash
selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception: Chrome version must be >= 65.0.3325.0
```

This is the code that I added to my project.
In `.travis.yml`:
```yaml
dist: trusty
before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
addons:
  chrome: stable
```

new test file (test_client.py) with:
```python
# A Helium function:
from helium import start_chrome, kill_browser


def test_home_page_load(client):
    driver = start_chrome(headless=True)
    kill_browser()
```

What I'm missing?
Thanks.
